const cacheName = 'v1';

const cacheAssets = [
  './bildirim.html',
'./css',
'./docs',
'./egitim.html',
'./fonts',
'./hakkinda.html',
'./img',
'./index.html',
'./js',
'./menu.html',
'./sw_sayfa.js',
'./sw_site.js',
'./css/bootstrap.min.css',
'./css/font-awesome.min.css',
'./css/signin.css',
'./css/style.css',
'./docs/temel_linux',
'./docs/temel_linux/1.html',
'./docs/temel_linux/10.html',
'./docs/temel_linux/11.html',
'./docs/temel_linux/12.html',
'./docs/temel_linux/13.html',
'./docs/temel_linux/14.html',
'./docs/temel_linux/15.html',
'./docs/temel_linux/16.html',
'./docs/temel_linux/17.html',
'./docs/temel_linux/18.html',
'./docs/temel_linux/19.html',
'./docs/temel_linux/2.html',
'./docs/temel_linux/20.html',
'./docs/temel_linux/21.html',
'./docs/temel_linux/22.html',
'./docs/temel_linux/23.html',
'./docs/temel_linux/24.html',
'./docs/temel_linux/3.html',
'./docs/temel_linux/4.html',
'./docs/temel_linux/5.html',
'./docs/temel_linux/6.html',
'./docs/temel_linux/7.html',
'./docs/temel_linux/8.html',
'./docs/temel_linux/9.html',
'./fonts/FontAwesome.otf',
'./fonts/fontawesome-webfont.eot',
'./fonts/fontawesome-webfont.svg',
'./fonts/fontawesome-webfont.ttf',
'./fonts/fontawesome-webfont.woff',
'./fonts/fontawesome-webfont.woff2',
'./img/0- Gerekli Ortamın Kurulması',
'./img/1- Komut Satırı',
'./img/10- Süreç İşlemleri',
'./img/11-Disk İşlemleri',
'./img/12- Çalışma Seviyeleri(Runlevels)',
'./img/13- Sembolik Link Ve Katı Link',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri',
'./img/15- Joker Karakterler',
'./img/16- Ağ Komutları',
'./img/17- Vim Editörü',
'./img/18- Konsol Üzerinden Dosya İndirmek',
'./img/19- Zamanlanmış Görevler',
'./img/2- Yardım Alma Komutları',
'./img/20- Log Dosyaları',
'./img/21-Sistem Görünümünü Özelleştirme',
'./img/3- Bilgi Alma Komutları',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi',
'./img/5- Dizin İşlemleri',
'./img/6- Dosya İşlemleri',
'./img/7- Dosya Arşivleme',
'./img/8- Erişim Yetkileri',
'./img/9- Kullanıcı İşlemleri',
'./img/menu',
'./img/0- Gerekli Ortamın Kurulması/1-min.png',
'./img/0- Gerekli Ortamın Kurulması/boot-menu.jpg',
'./img/1- Komut Satırı/0-min.png',
'./img/1- Komut Satırı/10-min.png',
'./img/1- Komut Satırı/11-min.png',
'./img/1- Komut Satırı/12-min.png',
'./img/1- Komut Satırı/13-min.png',
'./img/1- Komut Satırı/14-min.png',
'./img/1- Komut Satırı/15-min.png',
'./img/1- Komut Satırı/16-min.png',
'./img/1- Komut Satırı/17-min.png',
'./img/1- Komut Satırı/18-min.png',
'./img/1- Komut Satırı/19-min.png',
'./img/1- Komut Satırı/1-min.png',
'./img/1- Komut Satırı/20-min.png',
'./img/1- Komut Satırı/21-min.png',
'./img/1- Komut Satırı/22-min.png',
'./img/1- Komut Satırı/23-min.png',
'./img/1- Komut Satırı/24-min.png',
'./img/1- Komut Satırı/25-min.png',
'./img/1- Komut Satırı/26-min.png',
'./img/1- Komut Satırı/27-min.png',
'./img/1- Komut Satırı/28-min.png',
'./img/1- Komut Satırı/29-min.png',
'./img/1- Komut Satırı/2-min.png',
'./img/1- Komut Satırı/30-min.gif',
'./img/1- Komut Satırı/31-min.gif',
'./img/1- Komut Satırı/32-min.png',
'./img/1- Komut Satırı/33-min.png',
'./img/1- Komut Satırı/34-min.png',
'./img/1- Komut Satırı/35-min.png',
'./img/1- Komut Satırı/36-min.gif',
'./img/1- Komut Satırı/37-min.gif',
'./img/1- Komut Satırı/3-min.gif',
'./img/1- Komut Satırı/4-min.png',
'./img/1- Komut Satırı/5-min.png',
'./img/1- Komut Satırı/6-min.png',
'./img/1- Komut Satırı/7-min.png',
'./img/1- Komut Satırı/7.1-min.png',
'./img/1- Komut Satırı/7.2-min.png',
'./img/1- Komut Satırı/7.3-min.png',
'./img/1- Komut Satırı/7.4-min.png',
'./img/1- Komut Satırı/7.5-min.png',
'./img/1- Komut Satırı/7.6-min.png',
'./img/1- Komut Satırı/7.7-min.png',
'./img/1- Komut Satırı/8-min.png',
'./img/1- Komut Satırı/9-min.png',
'./img/1- Komut Satırı/diagram-min.png',
'./img/1- Komut Satırı/shell-kernel-min.png',
'./img/10- Süreç İşlemleri/10-min.png',
'./img/10- Süreç İşlemleri/11-min.png',
'./img/10- Süreç İşlemleri/12-min.png',
'./img/10- Süreç İşlemleri/13-min.png',
'./img/10- Süreç İşlemleri/14-min.png',
'./img/10- Süreç İşlemleri/15-min.png',
'./img/10- Süreç İşlemleri/16-min.png',
'./img/10- Süreç İşlemleri/17-min.png',
'./img/10- Süreç İşlemleri/18-min.png',
'./img/10- Süreç İşlemleri/19-min.gif',
'./img/10- Süreç İşlemleri/1-min.png',
'./img/10- Süreç İşlemleri/20-min.png',
'./img/10- Süreç İşlemleri/21-min.png',
'./img/10- Süreç İşlemleri/22-min.png',
'./img/10- Süreç İşlemleri/23-min.gif',
'./img/10- Süreç İşlemleri/24-min.gif',
'./img/10- Süreç İşlemleri/2-min.png',
'./img/10- Süreç İşlemleri/3-min.png',
'./img/10- Süreç İşlemleri/4-min.png',
'./img/10- Süreç İşlemleri/5-min.png',
'./img/10- Süreç İşlemleri/6-min.png',
'./img/10- Süreç İşlemleri/7-min.png',
'./img/10- Süreç İşlemleri/8-min.png',
'./img/10- Süreç İşlemleri/9-min.gif',
'./img/11-Disk İşlemleri/10-min.png',
'./img/11-Disk İşlemleri/11-min.gif',
'./img/11-Disk İşlemleri/12-min.gif',
'./img/11-Disk İşlemleri/13-min.png',
'./img/11-Disk İşlemleri/14-min.png',
'./img/11-Disk İşlemleri/15-min.png',
'./img/11-Disk İşlemleri/16-min.png',
'./img/11-Disk İşlemleri/17-min.png',
'./img/11-Disk İşlemleri/18-min.png',
'./img/11-Disk İşlemleri/19-min.gif',
'./img/11-Disk İşlemleri/19-min.png',
'./img/11-Disk İşlemleri/1-min.png',
'./img/11-Disk İşlemleri/20-min.png',
'./img/11-Disk İşlemleri/21-1-min.png',
'./img/11-Disk İşlemleri/21-min.png',
'./img/11-Disk İşlemleri/22-min.png',
'./img/11-Disk İşlemleri/23-min.gif',
'./img/11-Disk İşlemleri/23-min.png',
'./img/11-Disk İşlemleri/24-min.gif',
'./img/11-Disk İşlemleri/24-min.png',
'./img/11-Disk İşlemleri/2-min.png',
'./img/11-Disk İşlemleri/3-min.png',
'./img/11-Disk İşlemleri/4-min.png',
'./img/11-Disk İşlemleri/5-min.png',
'./img/11-Disk İşlemleri/6-min.png',
'./img/11-Disk İşlemleri/7-min.png',
'./img/11-Disk İşlemleri/8-min.png',
'./img/11-Disk İşlemleri/9-min.gif',
'./img/11-Disk İşlemleri/9-min-1.gif',
'./img/12- Çalışma Seviyeleri(Runlevels)/1-min.png',
'./img/12- Çalışma Seviyeleri(Runlevels)/2-min.png',
'./img/12- Çalışma Seviyeleri(Runlevels)/3-min.png',
'./img/12- Çalışma Seviyeleri(Runlevels)/4-min.png',
'./img/12- Çalışma Seviyeleri(Runlevels)/5-min.png',
'./img/12- Çalışma Seviyeleri(Runlevels)/6-min.gif',
'./img/12- Çalışma Seviyeleri(Runlevels)/runlevel.png',
'./img/13- Sembolik Link Ve Katı Link/10-min.png',
'./img/13- Sembolik Link Ve Katı Link/11-min.png',
'./img/13- Sembolik Link Ve Katı Link/1-min.png',
'./img/13- Sembolik Link Ve Katı Link/2-min.png',
'./img/13- Sembolik Link Ve Katı Link/3-min.png',
'./img/13- Sembolik Link Ve Katı Link/4-min.png',
'./img/13- Sembolik Link Ve Katı Link/5-min.png',
'./img/13- Sembolik Link Ve Katı Link/6-min.png',
'./img/13- Sembolik Link Ve Katı Link/7-min.png',
'./img/13- Sembolik Link Ve Katı Link/8-min.png',
'./img/13- Sembolik Link Ve Katı Link/9-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/10-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/11-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/12-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/13-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/14-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/15-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/16-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/17-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/1-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/2_1-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/2-min.png',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/3-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/4-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/5-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/6-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/7-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/8-min.gif',
'./img/14- Güncelleme Kurma Kaldırma İşlemleri/9-min.gif',
'./img/15- Joker Karakterler/10-min.png',
'./img/15- Joker Karakterler/11-min.png',
'./img/15- Joker Karakterler/12-min.png',
'./img/15- Joker Karakterler/13-min.png',
'./img/15- Joker Karakterler/1-min.png',
'./img/15- Joker Karakterler/2-min.png',
'./img/15- Joker Karakterler/3-min.png',
'./img/15- Joker Karakterler/4-min.png',
'./img/15- Joker Karakterler/5-min.png',
'./img/15- Joker Karakterler/6-min.png',
'./img/15- Joker Karakterler/7-min.png',
'./img/15- Joker Karakterler/8-min.png',
'./img/15- Joker Karakterler/9-min.png',
'./img/16- Ağ Komutları/10-min.png',
'./img/16- Ağ Komutları/11-min.png',
'./img/16- Ağ Komutları/12-min.png',
'./img/16- Ağ Komutları/13-min.png',
'./img/16- Ağ Komutları/14-min.png',
'./img/16- Ağ Komutları/15-min.png',
'./img/16- Ağ Komutları/16-min.png',
'./img/16- Ağ Komutları/17-min.png',
'./img/16- Ağ Komutları/18-min.png',
'./img/16- Ağ Komutları/19-min.png',
'./img/16- Ağ Komutları/1-min.png',
'./img/16- Ağ Komutları/20-min.png',
'./img/16- Ağ Komutları/2-min.png',
'./img/16- Ağ Komutları/3-min.png',
'./img/16- Ağ Komutları/4-min.png',
'./img/16- Ağ Komutları/5-min.png',
'./img/16- Ağ Komutları/6-min.png',
'./img/16- Ağ Komutları/7-min.gif',
'./img/16- Ağ Komutları/8-min.png',
'./img/16- Ağ Komutları/9-min.png',
'./img/17- Vim Editörü/10-min.gif',
'./img/17- Vim Editörü/11-min.gif',
'./img/17- Vim Editörü/12-min.gif',
'./img/17- Vim Editörü/13-min.gif',
'./img/17- Vim Editörü/14-min.png',
'./img/17- Vim Editörü/15-min.png',
'./img/17- Vim Editörü/16-min.gif',
'./img/17- Vim Editörü/17-min.gif',
'./img/17- Vim Editörü/1-min.png',
'./img/17- Vim Editörü/2-min.png',
'./img/17- Vim Editörü/3-min.gif',
'./img/17- Vim Editörü/4-min.png',
'./img/17- Vim Editörü/5-min.gif',
'./img/17- Vim Editörü/6-min.png',
'./img/17- Vim Editörü/7-min.gif',
'./img/17- Vim Editörü/8-min.gif',
'./img/17- Vim Editörü/9-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/10-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/11-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/1-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/2-min.png',
'./img/18- Konsol Üzerinden Dosya İndirmek/3-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/4-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/5-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/6-min.png',
'./img/18- Konsol Üzerinden Dosya İndirmek/7-min.gif',
'./img/18- Konsol Üzerinden Dosya İndirmek/8-min.png',
'./img/18- Konsol Üzerinden Dosya İndirmek/9-min.gif',
'./img/19- Zamanlanmış Görevler/10-min.png',
'./img/19- Zamanlanmış Görevler/11-min.png',
'./img/19- Zamanlanmış Görevler/12-min.png',
'./img/19- Zamanlanmış Görevler/1-min.png',
'./img/19- Zamanlanmış Görevler/2-min.png',
'./img/19- Zamanlanmış Görevler/3-min.png',
'./img/19- Zamanlanmış Görevler/4-min.png',
'./img/19- Zamanlanmış Görevler/5-min.png',
'./img/19- Zamanlanmış Görevler/6-min.png',
'./img/19- Zamanlanmış Görevler/7-min.png',
'./img/19- Zamanlanmış Görevler/8-min.png',
'./img/19- Zamanlanmış Görevler/9-min.png',
'./img/2- Yardım Alma Komutları/10-min.png',
'./img/2- Yardım Alma Komutları/11-min.png',
'./img/2- Yardım Alma Komutları/12-min.png',
'./img/2- Yardım Alma Komutları/13-min.png',
'./img/2- Yardım Alma Komutları/14-min.png',
'./img/2- Yardım Alma Komutları/1-min.png',
'./img/2- Yardım Alma Komutları/2-min.png',
'./img/2- Yardım Alma Komutları/3-min.png',
'./img/2- Yardım Alma Komutları/4-min.png',
'./img/2- Yardım Alma Komutları/5-min.png',
'./img/2- Yardım Alma Komutları/6-min.png',
'./img/2- Yardım Alma Komutları/7-min.png',
'./img/2- Yardım Alma Komutları/8-min.png',
'./img/2- Yardım Alma Komutları/9-min.png',
'./img/20- Log Dosyaları/10-min.png',
'./img/20- Log Dosyaları/1-min.png',
'./img/20- Log Dosyaları/2-min.png',
'./img/20- Log Dosyaları/3-min.png',
'./img/20- Log Dosyaları/4-min.png',
'./img/20- Log Dosyaları/5-min.png',
'./img/20- Log Dosyaları/6-min.png',
'./img/20- Log Dosyaları/7-min.png',
'./img/20- Log Dosyaları/8-min.png',
'./img/20- Log Dosyaları/9-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/10-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/1-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/2-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/3-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/4-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/5-min.jpg',
'./img/21-Sistem Görünümünü Özelleştirme/6-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/7-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/8-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/9-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/awesome-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/cinnamon-min.jpg',
'./img/21-Sistem Görünümünü Özelleştirme/desktop-env-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/dwm-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/e17-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/fluxbox-1-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/fluxbox-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/gorunum-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/i3-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/imlec-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/kabuk-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/kde-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/lxde-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/mate-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/openbox-1-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/openbox-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/ortm_1-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/ortm_2-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/simgeler-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/tweaks-min.gif',
'./img/21-Sistem Görünümünü Özelleştirme/xfce-min.png',
'./img/21-Sistem Görünümünü Özelleştirme/xmonad-min.png',
'./img/3- Bilgi Alma Komutları/0-min.png',
'./img/3- Bilgi Alma Komutları/10-min.png',
'./img/3- Bilgi Alma Komutları/11-min.gif',
'./img/3- Bilgi Alma Komutları/12-min.png',
'./img/3- Bilgi Alma Komutları/13-min.png',
'./img/3- Bilgi Alma Komutları/14-min.png',
'./img/3- Bilgi Alma Komutları/15-min.png',
'./img/3- Bilgi Alma Komutları/16-min.png',
'./img/3- Bilgi Alma Komutları/17-min.png',
'./img/3- Bilgi Alma Komutları/18-min.png',
'./img/3- Bilgi Alma Komutları/19-min.png',
'./img/3- Bilgi Alma Komutları/1-min.png',
'./img/3- Bilgi Alma Komutları/20-min.png',
'./img/3- Bilgi Alma Komutları/21-min.png',
'./img/3- Bilgi Alma Komutları/22-min.png',
'./img/3- Bilgi Alma Komutları/23-min.png',
'./img/3- Bilgi Alma Komutları/24-min.png',
'./img/3- Bilgi Alma Komutları/25-min.png',
'./img/3- Bilgi Alma Komutları/26-min.png',
'./img/3- Bilgi Alma Komutları/27-min.png',
'./img/3- Bilgi Alma Komutları/28-min.png',
'./img/3- Bilgi Alma Komutları/29-min.png',
'./img/3- Bilgi Alma Komutları/2-min.png',
'./img/3- Bilgi Alma Komutları/30-min.png',
'./img/3- Bilgi Alma Komutları/31-min.png',
'./img/3- Bilgi Alma Komutları/32-min.png',
'./img/3- Bilgi Alma Komutları/33-min.png',
'./img/3- Bilgi Alma Komutları/34-min.png',
'./img/3- Bilgi Alma Komutları/35-min.png',
'./img/3- Bilgi Alma Komutları/36-min.png',
'./img/3- Bilgi Alma Komutları/37-min.png',
'./img/3- Bilgi Alma Komutları/38-min.png',
'./img/3- Bilgi Alma Komutları/39-min.png',
'./img/3- Bilgi Alma Komutları/3-min.png',
'./img/3- Bilgi Alma Komutları/40-min.gif',
'./img/3- Bilgi Alma Komutları/4-min.png',
'./img/3- Bilgi Alma Komutları/5-min.jpg',
'./img/3- Bilgi Alma Komutları/6-min.png',
'./img/3- Bilgi Alma Komutları/7-min.png',
'./img/3- Bilgi Alma Komutları/8-min.png',
'./img/3- Bilgi Alma Komutları/9-min.png',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/1-min.png',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/2-min.gif',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/3-min.gif',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/4-min.gif',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/5-min.png',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/6-min.png',
'./img/4 -Linux Dosya Sistemi Hiyerarşisi/7-min.gif',
'./img/5- Dizin İşlemleri/10-min.png',
'./img/5- Dizin İşlemleri/11-min.png',
'./img/5- Dizin İşlemleri/12-min.png',
'./img/5- Dizin İşlemleri/13-min.png',
'./img/5- Dizin İşlemleri/14-min.png',
'./img/5- Dizin İşlemleri/15-min.png',
'./img/5- Dizin İşlemleri/16-min.png',
'./img/5- Dizin İşlemleri/17-min.png',
'./img/5- Dizin İşlemleri/18-min.png',
'./img/5- Dizin İşlemleri/19-min.png',
'./img/5- Dizin İşlemleri/1-min.png',
'./img/5- Dizin İşlemleri/20-min.png',
'./img/5- Dizin İşlemleri/21-min.png',
'./img/5- Dizin İşlemleri/22-min.png',
'./img/5- Dizin İşlemleri/23-min.png',
'./img/5- Dizin İşlemleri/24-min.png',
'./img/5- Dizin İşlemleri/25-min.png',
'./img/5- Dizin İşlemleri/26-min.png',
'./img/5- Dizin İşlemleri/27-min.png',
'./img/5- Dizin İşlemleri/28-min.png',
'./img/5- Dizin İşlemleri/2-min.png',
'./img/5- Dizin İşlemleri/3-min.png',
'./img/5- Dizin İşlemleri/4-min.png',
'./img/5- Dizin İşlemleri/5-min.png',
'./img/5- Dizin İşlemleri/6-min.png',
'./img/5- Dizin İşlemleri/7-min.png',
'./img/5- Dizin İşlemleri/8-min.gif',
'./img/5- Dizin İşlemleri/9-min.png',
'./img/6- Dosya İşlemleri/10-min.gif',
'./img/6- Dosya İşlemleri/11-min.png',
'./img/6- Dosya İşlemleri/12-min.png',
'./img/6- Dosya İşlemleri/13-min.png',
'./img/6- Dosya İşlemleri/14-min.png',
'./img/6- Dosya İşlemleri/15-min.png',
'./img/6- Dosya İşlemleri/16-min.png',
'./img/6- Dosya İşlemleri/17-min.png',
'./img/6- Dosya İşlemleri/18-min.png',
'./img/6- Dosya İşlemleri/19-min.png',
'./img/6- Dosya İşlemleri/1-min.png',
'./img/6- Dosya İşlemleri/20-min.png',
'./img/6- Dosya İşlemleri/21-min.png',
'./img/6- Dosya İşlemleri/22-min.png',
'./img/6- Dosya İşlemleri/23-min.png',
'./img/6- Dosya İşlemleri/24-min.png',
'./img/6- Dosya İşlemleri/25-min.png',
'./img/6- Dosya İşlemleri/26-min.png',
'./img/6- Dosya İşlemleri/27-min.png',
'./img/6- Dosya İşlemleri/28-min.png',
'./img/6- Dosya İşlemleri/29-min.png',
'./img/6- Dosya İşlemleri/2-min.png',
'./img/6- Dosya İşlemleri/30-min.png',
'./img/6- Dosya İşlemleri/31-min.png',
'./img/6- Dosya İşlemleri/32-min.png',
'./img/6- Dosya İşlemleri/33-min.png',
'./img/6- Dosya İşlemleri/34-min.png',
'./img/6- Dosya İşlemleri/35-min.png',
'./img/6- Dosya İşlemleri/36-min.png',
'./img/6- Dosya İşlemleri/37-min.png',
'./img/6- Dosya İşlemleri/38-min.png',
'./img/6- Dosya İşlemleri/39-min.png',
'./img/6- Dosya İşlemleri/3-min.png',
'./img/6- Dosya İşlemleri/40-min.png',
'./img/6- Dosya İşlemleri/41-min.png',
'./img/6- Dosya İşlemleri/42-min.png',
'./img/6- Dosya İşlemleri/43-min.png',
'./img/6- Dosya İşlemleri/44-min.png',
'./img/6- Dosya İşlemleri/45-min.png',
'./img/6- Dosya İşlemleri/46-min.png',
'./img/6- Dosya İşlemleri/47-min.png',
'./img/6- Dosya İşlemleri/48-min.png',
'./img/6- Dosya İşlemleri/49-min.png',
'./img/6- Dosya İşlemleri/4-min.png',
'./img/6- Dosya İşlemleri/50-min.png',
'./img/6- Dosya İşlemleri/51-min.png',
'./img/6- Dosya İşlemleri/52-min.png',
'./img/6- Dosya İşlemleri/53-min.png',
'./img/6- Dosya İşlemleri/54-min.png',
'./img/6- Dosya İşlemleri/55-min.png',
'./img/6- Dosya İşlemleri/56-min.png',
'./img/6- Dosya İşlemleri/57-min.png',
'./img/6- Dosya İşlemleri/58-min.png',
'./img/6- Dosya İşlemleri/5-min.png',
'./img/6- Dosya İşlemleri/6-min.png',
'./img/6- Dosya İşlemleri/7-min.png',
'./img/6- Dosya İşlemleri/8-min.gif',
'./img/6- Dosya İşlemleri/9-min.gif',
'./img/7- Dosya Arşivleme/10-min.png',
'./img/7- Dosya Arşivleme/11-min.png',
'./img/7- Dosya Arşivleme/12-min.png',
'./img/7- Dosya Arşivleme/13-min.png',
'./img/7- Dosya Arşivleme/14-min.png',
'./img/7- Dosya Arşivleme/15-min.png',
'./img/7- Dosya Arşivleme/1-min.png',
'./img/7- Dosya Arşivleme/2-min.png',
'./img/7- Dosya Arşivleme/3-min.png',
'./img/7- Dosya Arşivleme/4-min.png',
'./img/7- Dosya Arşivleme/5-min.png',
'./img/7- Dosya Arşivleme/6-min.png',
'./img/7- Dosya Arşivleme/7-min.png',
'./img/7- Dosya Arşivleme/8-min.png',
'./img/7- Dosya Arşivleme/9-min.png',
'./img/8- Erişim Yetkileri/10-min.png',
'./img/8- Erişim Yetkileri/11-min.png',
'./img/8- Erişim Yetkileri/12-min.png',
'./img/8- Erişim Yetkileri/13-min.png',
'./img/8- Erişim Yetkileri/14-min.png',
'./img/8- Erişim Yetkileri/1-min.png',
'./img/8- Erişim Yetkileri/2-min.png',
'./img/8- Erişim Yetkileri/3-min.png',
'./img/8- Erişim Yetkileri/4-min.png',
'./img/8- Erişim Yetkileri/5-min.png',
'./img/8- Erişim Yetkileri/6-min.png',
'./img/8- Erişim Yetkileri/7-min.png',
'./img/8- Erişim Yetkileri/8-min.png',
'./img/8- Erişim Yetkileri/9-min.png',
'./img/9- Kullanıcı İşlemleri/0-min.png',
'./img/9- Kullanıcı İşlemleri/10-min.png',
'./img/9- Kullanıcı İşlemleri/11-min.png',
'./img/9- Kullanıcı İşlemleri/12-min.png',
'./img/9- Kullanıcı İşlemleri/13-min.png',
'./img/9- Kullanıcı İşlemleri/14-min.png',
'./img/9- Kullanıcı İşlemleri/15-min.png',
'./img/9- Kullanıcı İşlemleri/16-min.png',
'./img/9- Kullanıcı İşlemleri/17-min.png',
'./img/9- Kullanıcı İşlemleri/18-min.png',
'./img/9- Kullanıcı İşlemleri/19-min.png',
'./img/9- Kullanıcı İşlemleri/1-min.png',
'./img/9- Kullanıcı İşlemleri/20-min.png',
'./img/9- Kullanıcı İşlemleri/21-min.png',
'./img/9- Kullanıcı İşlemleri/22-min.png',
'./img/9- Kullanıcı İşlemleri/23-min.gif',
'./img/9- Kullanıcı İşlemleri/24-min.png',
'./img/9- Kullanıcı İşlemleri/25-min.png',
'./img/9- Kullanıcı İşlemleri/26-min.png',
'./img/9- Kullanıcı İşlemleri/27-min.png',
'./img/9- Kullanıcı İşlemleri/28-min.png',
'./img/9- Kullanıcı İşlemleri/29-min.png',
'./img/9- Kullanıcı İşlemleri/2-min.png',
'./img/9- Kullanıcı İşlemleri/30-min.png',
'./img/9- Kullanıcı İşlemleri/3-min.png',
'./img/9- Kullanıcı İşlemleri/4-min.png',
'./img/9- Kullanıcı İşlemleri/5-min.png',
'./img/9- Kullanıcı İşlemleri/6-min.png',
'./img/9- Kullanıcı İşlemleri/7-min.png',
'./img/9- Kullanıcı İşlemleri/8-min.png',
'./img/9- Kullanıcı İşlemleri/9-min.png',
'./img/menu/pc-logo.png',
'./img/menu/book_1.png',
'./img/menu/content.png',
'./img/menu/icon.png',
'./img/menu/laptop1.png',
'./img/menu/logo.png',
'./img/menu/opt.gif',
'./img/menu/quest.png',
'./img/menu/refund.png',
'./img/menu/test.png',
'./img/menu/vdoply.png',
'./js/bootstrap.min.js',
'./js/form-submission-handler.js',
'./js/jquery-3.3.1.slim.min.js',
'./js/main.js',
'./js/script.js'

];


self.addEventListener('install', e => {
  console.log('Service Worker: Installed');

  e.waitUntil(
    caches
      .open(cacheName)
      .then(cache => {
        console.log('Service Worker: Caching Files');
        cache.addAll(cacheAssets);
      })
      .then(() => self.skipWaiting())
  );
});


self.addEventListener('activate', e => {
  console.log('Service Worker: Activated');
  
  e.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cache => {
          if (cache !== cacheName) {
            console.log('Service Worker: Clearing Old Cache');
            return caches.delete(cache);
          }
        })
      );
    })
  );
});


self.addEventListener('fetch', e => {
  console.log('Service Worker: Fetching');
  e.respondWith(fetch(e.request).catch(() => caches.match(e.request)));
});
